### ISSUE TITLE
At-Least/At-Most generates faulty query

### ISSUE THREAD

**Issue by indrekpaas** [drewminns/qqui#2]
The second selector's `nth-last-child` has a (faulty) negative 'n' value.

The generated code is
```css
div:nth-last-child(n+2):nth-last-child(-n+4):first-child, 
div:nth-last-child(-n+2):nth-last-child(-n+4):first-child ~ div { }
```
but should be
```css
div:nth-last-child(n+2):nth-last-child(-n+4):first-child, 
div:nth-last-child(n+2):nth-last-child(-n+4):first-child ~ div { }
```

Validated this against QQ's source code.
