### ISSUE TITLE
Enhancement: Add options for additional operators

### ISSUE THREAD

**Issue by indrekpaas** [drewminns/qqui#3]
```css
div:nth-last-child(8):first-child,
div:nth-last-child(8):first-child ~ div {
  /* Exactly 8 */
}
```
```css
div:nth-last-child(n+8):nth-last-child(-n+12):first-child,
div:nth-last-child(n+8):nth-last-child(-n+12):first-child ~ div {
  /* At least 8 and at most 12 */
}
```
```css
div:nth-last-child(-n+7):first-child,
div:nth-last-child(-n+7):first-child ~ div {
  /* Less than 8 */
}
```
```css
div:nth-last-child(-n+8):first-child,
div:nth-last-child(-n+8):first-child ~ div {
  /* Less than or equal to 8 */
}
```
```css
div:nth-last-child(n+9),
div:nth-last-child(n+9) ~ div {
  /* More than 8 */
}
```
```css
div:nth-last-child(n+8),
div:nth-last-child(n+8) ~ div {
  /* More than or equal to 8 */
}
```
